version: '3'
services:
  odoo:
    image: odoo:16.0
    platform: linux/x86_64
    container_name: odoo
    restart: unless-stopped
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "8211:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - webnet
  db:
    image: postgres:14.0
    platform: linux/x86_64
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5210:5432"
    volumes:
      - db-data:/var/lib/postgresql/odoo
    networks:
      - webnet

volumes:
  odoo-data:
  db-data:

networks:
  webnet:
